[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.95

[general]
import = ["/home/axwain/.config/alacritty/themes/palenight.toml"]


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
